#!/usr/bin/env perl
use Modern::Perl;
use Getopt::Long::Descriptive;
             
my ($opt, $usage) = describe_options(
   '%c %o',  
   [ 'i=s',     "input file" ],
   [ 'o=s',     "output file" ],
   [ 'start=s', "start position" ],
   [ 'end=s',   "end position" ],
   [ 'help',    "print usage message and exit" ],
   [ 'n',       "print command" ],
 );          
print($usage->text), exit if $opt->{help} or ! keys %$opt;
$opt->{i} and $opt->{o} or say("input or output file not specified, aborting"), exit;
my @args = ('ffmpeg');
push @args, "-i $opt->{i}";
push @args, "-ss $opt->{start}" if $opt->{start};
push @args, "-to $opt->{end}" if defined $opt->{end};
push @args, "-copyts"; # so that -to argument is properly handled
push @args, "-strict -2";
push @args, "$opt->{o}";
my $cmd = join " ",@args;
say $cmd;
system($cmd) unless $opt->{n};
