#!/usr/bin/env perl
package App::fftrim;
use 5.006;
use strict;
use warnings;
use App::fftrim;
use Path::Tiny;
use autodie ':all';
use feature 'say';
use Cwd;
use Getopt::Long::Descriptive;
our ($opt, $usage) = describe_options(
   '%c %o',
   [ 'in=s',			"input file(s)"],
   [ 'out=s',			"output file"],
   [ 'start=s',			"start time"],
   [ 'end=s',			"end time"],
   [ 'profile=s',       'merge ffmpeg options from named file in $HOME/.fftrim'],
   [ 'source-dir=s',  	"batch mode, source directory" ],
   [ 'target-dir=s',	"batch mode, destination directory" ],
   [ 'frame-rate|r=s',  "specify frame rate" ],
   [ 'auto-frame-rate|a',"use same frame rate as source" ],
   [ 'n',      			"simulate: print commands but do not run them" ],
   [ 'm',      			"simulate: print commands omitting file checks" ],
   [ 'old-concat',		"old naming for intermediate file" ],
   [ 'help',   			"print usage message and exit" ],
 );
initial_setup() and exit;
print($usage->text, 
	"\nNote that --in, --out, --start and --end options are not available with batch mode\n"),
	exit if $opt->{help} or ! keys %$opt;

process_args();


__DATA__
# change the following ffmpeg options as suits

-c:v libx264
-preset:v medium
-profile:v main
-tune:v film
-s:v 640x360
-c:a aac
-b:a 80k
-ac 2
-ar 24000
-level 3

# don't change these arguments
-strict -2

=head1 NAME

B<fftrim> - concatenate, trim and compress video files

=head2 Synopsis

C<fftrim --in 00001.MTS --out clip1.mp4 --start 15.5 --end 44:13>

C<fftrim --in "00001.MTS 00002.MTS" --out clip2.mp4 --start 44:13 --end 2-1:12>

=head2 Description

B<fftrim> processes raw videos from a camcorder by
concatenating, trimming and compressing them
according to arguments you supply on the 
command line, or in a F<CONTROL> file.

=head3 Processing a single file

C<fftrim --in 00001.MTS --out clip1.mp4 --start 15.5 --end 44:13>

=head3 Handling concatenated sources

C<fftrim --in "00001.MTS 00002.MTS 00003.MTS" --out clip2.mp4 --start 44:13 --end 2-1:12>

C<fftrim --in "00001.MTS 00002.MTS 00003.MTS" --out clip2.mp4 --start 2-1:12 --end 3-1:05>

The expression C<2-1:12> means a position in the concatenated
file that includes the full length of the first clip and
1:12 minutes of the second clip. Similarly, C<3-65> or
C<3-1:05> would mean a position of 1:05 into the third clip.

The source files are concatenated into an intermediate file
using the name of the first source file appended with .mp4.

=head3 Batch mode

C<fftrim --source-dir raw --target-dir final>

=head3 CONTROL file format

The CONTROL file is used for batch processing
and appears in the same directory as the source
video files. It contains multiple lines
of the following format:

    # source file(s)    output file   start  end
    # ---------------   -----------   -----  ----
      00001.MTS       : part1.mp4   : 15.5 : 44:13 

Arguments are separated by a colon character
flanked by whitespace. Commented lines are ignored.

The following line creates F<part2.mp4> from source files
F<00001.MTS> and F<00002.MTS>:

    00001.MTS 00002.MTS : part2.mp4 :  44:13 : 2-24:55 

The extracted video starts 44:13 into the first source file.
and ends 24:55 from the start of the second file.

=head3 Profiles

F<$HOME/.fftrim> is the directory for profiles, 
which are text files containing ffmpeg options. 

Adding C<--profile highres> to the command line will
merge options from the file F<$HOME/.fftrim/highres>.

Be sure to look at F<$HOME/.fftrim/default>. These options are
are merged by default, that is when C<--profile> is not supplied.
Please change them to suit yourself.

=head3 Help

  fftrim [-mnr] [long options...]
  	--in STR          input file(s)
  	--out STR         output file
  	--start STR       start time
  	--end STR         end time
  	--profile STR     merge ffmpeg options from named file in
  	                  $HOME/.fftrim
  	--source-dir STR  batch mode, source directory
  	--target-dir STR  batch mode, destination directory
  	-r --frame-rate   specify framerate (with no arg: fallback to source
  	                  file frame rate)
  	-n                simulate: print commands but do not run them
  	-m                simulate: print commands omitting file checks
  	--old-concat      old naming for intermediate file
  	--help            print usage message and exit
  
  Note that --in, --out, --start and --end options are not available in batch mode

=head3 Bugs

Please report any bugs you encounter.

