#!/usr/bin/env perl
package App::fftrim;
use 5.006;
use strict;
use warnings;
use App::fftrim;
use Path::Tiny;
use autodie ':all';
use feature 'say';
use Cwd;
use Getopt::Long::Descriptive;
our ($opt, $usage) = describe_options(
   '%c %o',
   [ 'in=s',			"input file(s)"],
   [ 'out=s',			"output file"],
   [ 'start=s',			"start time"],
   [ 'end=s',			"end time"],
   [ 'profile=s',       'merge ffmpeg options from named file in $HOME/.fftrim'],
   [ 'source-dir=s',  	"batch mode, source directory" ],
   [ 'target-dir=s',	"batch mode, destination directory" ],
   [ 'c',      			"make output files conform to source file frame rate" ],
   [ 'n',      			"simulate: show output commands but do not run them" ],
   [ 'm',      			"simulate: show output commands omitting file checks" ],
   [ 'old-concat',		"use old, broken naming style for concat target" ],
   [ 'help',   			"print usage message and exit" ],
 );
print($usage->text, 
	"\nNote that --in, --out, --start and --end options are not available with batch mode\n"),
	exit if $opt->{help} or ! keys %$opt;

process_args();


__DATA__
# change the following ffmpeg arguments to suit
-c:v libx264
-preset:v medium
-profile:v main
-tune:v film
-s:v 640x360
-c:a aac
-b:a 80k
-ac 2
-ar 24000
-level 3

# don't change these arguments
-strict -2
# -copyts # causes problem rendering 20180923-2
